### ISSUE TITLE
The Main Algorithm of The Plugin

### ISSUE THREAD

**Issue by TommyHy9556** [hellguz/Magnetizing_FloorPlanGenerator#1]
Hi, I am a student in Upenn. I am really impressed by you plugin. Can you talk about the main algorithm of the plugin. I am also interesting in generative design. Is the algorithm generic algorithm or Bayesion network? Thank you!

**Comment by hellguz** [comment]
Hi! Sorry for late answer, somewhy don't get notifications about messages here. If you're still interested, you can contact me via email or skype (hellguz@gmail.com) freely! And here you can get some of basic ideas of the project. 

https://www.dropbox.com/s/pa5y1aupniq9cej/Revisiting%20Ideas5_s.pdf?dl=0
